### ISSUE TITLE
Manual Installation Instructions Extensions missing

### ISSUE THREAD

**Issue by bpolania** [alaphao/RLPSwift#3]
Manual installation instructions specify that in order to install developers must 

> Download and drop RLP.swift inside your project.

but it's also required to import the `UInt32+Extensions.swift` file

I also suggest to rename `UInt32+Extensions.swift` to `UInt32+byteArrayLittleEndian.swift`

**Comment by alephao** [comment]
@bpolania I haven't checked this repo in a long time 🙈

Thanks for pointing out the mistake, and suggesting the change, will add as soon as I can!

**Comment by alephao** [comment]
I removed the Manual installation instructions for now.

Please feel free to make a PR adding it 😄
